# GitHub Pages Configuration for Truncate Website

# Site settings
title: Truncate - AI Legal Work Environment
description: The worlds first integrated AI environment for legal professionals
url: "" # Add your GitHub Pages URL when deployed

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Custom variables
version: "1.0.0"
release_date: "March 5, 2025"
